project:
  type: website

website:
  title: "shusuh-pop.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: education.qmd
        text: 教育经历
      - href: honors.qmd
        text: 荣誉奖项
      - href: contact.qmd
        text: 联系我
      - about.qmd

format:
  html:
    theme:
      - darkly
      - brand
    css: styles.css
    toc: true



